name: Build Image

on:
  workflow_dispatch:
    inputs:
      imageName:
        description: 'Image Name'
        required: true
      tagName:
        description: 'Tag Name'
        required: true

jobs:

  build:
    name: Build ${{ github.event.inputs.imageName }}:${{ github.event.inputs.tagName }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Clone Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: make install

      - name: ORCA Generate
        run: make generate -B

      - name: Build Image
        run: make build image=${{ github.event.inputs.imageName }} tag=${{ github.event.inputs.tagName }} -B

      - name: Run SVRUnit Tests
        run: make test image=${{ github.event.inputs.imageName }} tag=${{ github.event.inputs.tagName }} -B

      - name: Store SVRUnit Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: svrunit_report_${{ github.event.inputs.imageName }}_${{ github.event.inputs.tagName }}
          retention-days: 3
          path: |
            .reports

      - name: Build JUnit Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: SVRUnit Tests
          path: .reports/report.xml
          reporter: jest-junit

      - name: Start Image
        run: |
          docker run --rm -p 80:80 --name app -d nevercodealone/${{ github.event.inputs.imageName }}:${{ github.event.inputs.tagName }}
          sleep 10
          docker logs app

      - name: Install Cypress
        run: cd tests/cypress && make install -B

      - name: Run Cypress Tests
        run: |
          cd tests/cypress && make run url=http://localhost

      - name: Store Cypress Results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress_results_${{ github.event.inputs.imageName }}_${{ github.event.inputs.tagName }}
          retention-days: 1
          path: |
            tests/cypress/cypress/videos
            tests/cypress/cypress/screenshots